---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
  name: age-gender-estimator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: age-gender-estimator
        version: v1
    spec:
      volumes:
      - hostPath:
          path: /dev/video0
        name: videosource
      containers:
      - image: gokulpch/age-gender-detection:v1.0
        imagePullPolicy: IfNotPresent
        name: age-gender-estimator
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/video0
          name: videosource
